# Generated by Django 3.0.3 on 2020-06-03 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hospitale',
            new_name='Hospital',
        ),
    ]
