# Generated by Django 3.0.3 on 2020-06-04 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0003_auto_20200603_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='TOTAL_CAMAS_AREA_HOSPITALIZACION',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='TOTAL_CAMAS_EN_OTRAS_AREAS_NO_HOSP',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='TOTAL_DE_CONSULTORIOS',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='TOTAL_DE_ENFERMERAS_EN_CONTACTO_CON_EL_PACIENTE',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='TOTAL_MEDICOS_GENERALES_Y_ESPECIALISTAS',
            field=models.IntegerField(null=True),
        ),
    ]
