# Generated by Django 3.0.3 on 2020-06-04 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0004_auto_20200603_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='NOMBRE_DE_LA_UNIDAD',
            field=models.CharField(max_length=255),
        ),
    ]
