# Generated by Django 3.0.3 on 2020-06-04 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0005_auto_20200603_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='CLAVE_INSTUTUCION',
            new_name='CLAVE_INSTITUCION',
        ),
    ]
